### ISSUE TITLE
--debug is deprecated 

### ISSUE THREAD

**Issue by mthsmlk** [ericclemmons/grunt-express-server#118]
Hello,

i updated my project and node.js to v8.9.3 with this grunt plugin and this warning appears on start :
(node:13920) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

But the server stops after this message.

I just changed `--debug` in  `/task/lib/server.js` to `--inspect` so this worked well now... but maybe you have to check node version and use debug or inspect... 

greetings

**Comment by nmarcetic** [comment]
Confirming. I am using node v8.9.4 same problem, @molethiaz your idea to hack the lib helped :)

**Comment by jdmcnair** [comment]
I'm confused. It looks like this issue was resolved in this commit: https://github.com/ericclemmons/grunt-express-server/commit/8156d6ea39597da06754024be699321773c136d7

But I don't see any new releases that have happened since then (Sep 15, 2017)? Latest release I see is [0.5.1](https://github.com/ericclemmons/grunt-express-server/releases/tag/v0.5.1) (Apr 3, 2015).

**Edit**: OK, actually it looks like there have been several releases, available on npm, that are not listed in the releases here on github. Version [0.5.4](https://www.npmjs.com/package/grunt-express-server/v/0.5.4) does include the fix for this, so it looks like this ticket can be closed.

**Comment by mthsmlk** [comment]
Thank you for clarifying. All right then I close the issue.
